################################################
###        TECH Properties               ####
################################################

# Spring Boot configuration
# [ LOCAL & DEV ]
server: 
  port: 9082
spring: 
  profiles: 
    active: dev
  datasource: # postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:log4jdbc:postgresql://localhost:5432/phs?currentSchema=demo
    username: postgres
    password: qwe123!!
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
  thymeleaf: 
    cache: false
    encoding: UTF-8
    prefix: classpath:/static/
    suffix: .html
  servlet: 
    multipart: 
      enabled: true
      file-size-threshold: 2KB   # Threshold after which files are written to disk.
      max-file-size: 200MB       # Max file size.
      max-request-size: 215MB    # Max Request Size   
mybatis: 
  type-aliases-package: com.sicc.sample.vo
  mapper-locations: classpath*:mapper/**/*.xml
  configuration: 
    cache-enabled: true
    lazy-loading-enabled: true
    map-underscore-to-camel-case: false
    default-fetch-size: 100
    default-statement-timeout: 30
    auto-mapping-unknown-column-behavior: FAILING
logging: 
  level: 
    sicc.tech: DEBUG
    org.springframework.web: DEBUG


---
# [ PRD ]
server: 
  port: 9082
spring: 
  profiles: prd
  datasource: # postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/demo
    username: postgres
    password: 0811
    driver-class-name: org.postgresql.Driver
  thymeleaf: 
    cache: false
    encoding: UTF-8
    prefix: classpath:/static/
    suffix: .html
  servlet: 
    multipart: 
      enabled: true
      file-size-threshold: 2KB   # Threshold after which files are written to disk.
      max-file-size: 200MB       # Max file size.
      max-request-size: 215MB    # Max Request Size  
mybatis: 
  type-aliases-package: com.sicc.sample.vo
  mapper-locations: classpath*:mapper/**/*.xml
  configuration: 
    cache-enabled: true
    lazy-loading-enabled: true
    map-underscore-to-camel-case: false
    default-fetch-size: 100
    default-statement-timeout: 30
    auto-mapping-unknown-column-behavior: FAILING
logging: 
  level: 
    sicc.tech: ERROR
    org.springframework.web: ERROR

